### ISSUE TITLE
Errors with pygplates.FeatureCollection.get arguments

### ISSUE THREAD

**Issue by cpalfonso** [GPlates/GPlates#2]
Specifying the arguments of the [`pygplates.FeatureCollection.get`](https://www.gplates.org/docs/pygplates/generated/pygplates.featurecollection#pygplates.FeatureCollection.get) method by name doesn't seem to work properly. For example, with the following setup:

```python
>>> import pygplates
>>> fc = pygplates.FeatureCollection(pygplates.Feature())
>>> feature_query = lambda _: True
>>> feature_return = pygplates.FeatureReturn.exactly_one  # the default value
```

Calling the method with positional arguments works as expected:

```python
>>> fc.get(feature_query)
<pygplates.pygplates.Feature object at 0x115be8ac0>
>>> fc.get(feature_query, feature_return)
<pygplates.pygplates.Feature object at 0x115be8ba0>
```

But if we try to use named arguments it results in some fairly strange errors:

```python
>>> fc.get(feature_query=feature_query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    FeatureCollection.get(FeatureCollection)
did not match C++ signature:
    get(GPlatesModel::FeatureCollectionHandle {lvalue}, boost::python::api::object feature_query, GPlatesApi::FeatureReturn::Value feature_query=pygplates.pygplates.FeatureReturn.exactly_one)
```

and

```python
>>> fc.get(feature_query=feature_query, feature_return=feature_return)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    FeatureCollection.get(FeatureCollection)
did not match C++ signature:
    get(GPlatesModel::FeatureCollectionHandle {lvalue}, boost::python::api::object feature_query, GPlatesApi::FeatureReturn::Value feature_query=pygplates.pygplates.FeatureReturn.exactly_one)
```

From the error message, it looks like the two arguments are somehow both named `feature_query`. Incidentally, this means that the following actually works:

```python
>>> fc.get(feature_query, feature_query=feature_return)
<pygplates.pygplates.Feature object at 0x115be8ac0>
```

As far as I can tell, the issue stems from this particular block here, which seems to be where the two arguments are given the same name:
https://github.com/GPlates/GPlates/blob/0d06fc9a8430dd66e7a857041f213a4acbee430f/src/api/PyFeatureCollection.cc#L1011-L1014

**Comment by jcannon-gplates** [comment]
Thanks for spotting that!  I've fixed (and added a test case). It'll be in the next release (soon).
